### ISSUE TITLE
Demo SQL file may prove problematic with Phabricator Upgrades

### ISSUE THREAD

**Issue by darkwing** [mozilla-conduit/demo#16]
The demo SQL file we automatically install with this demo could, in theory, be a problem because it creates tables.  If a Phabricator upgrade have its (possibly) modified tables overwritten and thus we'd be using an "old" database structure with a new set of phabricator PHP files?

Something we should consider.

**Comment by dklawren** [comment]
Solved by https://github.com/mozilla-services/mozphab/commit/f72e9ba936e4243028ad747e08be0d72d50df612
